services:
  - type: web
    name: aiorhuman-server
    env: node
    rootDir: human-ai-game/server
    buildCommand: |
      npm install
      npm install -g typescript
      npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://aiorhuman-18gpekkme-rajat-tiwaris-projects.vercel.app"
    healthCheckPath: /health